// <auto-generated />
using System;
using KoeretoejsManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoeretoejsManager.Api.Migrations
{
    [DbContext(typeof(KoeretoejsManagerDbContext))]
    [Migration("20260422111138_InitCreateUser")]
    partial class InitCreateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("KoeretoejsManager.Api.Models.DrivingLicense", b =>
                {
                    b.Property<int>("DrivingLicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrivingLicenseId");

                    b.ToTable("DrivingLicenses");

                    b.HasData(
                        new
                        {
                            DrivingLicenseId = 1,
                            Type = "Unknown"
                        },
                        new
                        {
                            DrivingLicenseId = 2,
                            Type = "B"
                        },
                        new
                        {
                            DrivingLicenseId = 3,
                            Type = "BE"
                        },
                        new
                        {
                            DrivingLicenseId = 4,
                            Type = "C"
                        },
                        new
                        {
                            DrivingLicenseId = 5,
                            Type = "C1"
                        },
                        new
                        {
                            DrivingLicenseId = 6,
                            Type = "CE"
                        },
                        new
                        {
                            DrivingLicenseId = 7,
                            Type = "C1E"
                        },
                        new
                        {
                            DrivingLicenseId = 8,
                            Type = "D"
                        });
                });

            modelBuilder.Entity("KoeretoejsManager.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KoeretoejsManager.Api.Models.UserDrivingLicense", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrivingLicenseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "DrivingLicenseId");

                    b.HasIndex("DrivingLicenseId");

                    b.ToTable("UserDrivingLicenses");
                });

            modelBuilder.Entity("KoeretoejsManager.Api.Models.UserDrivingLicense", b =>
                {
                    b.HasOne("KoeretoejsManager.Api.Models.DrivingLicense", "DrivingLicense")
                        .WithMany("UserDrivingLicense")
                        .HasForeignKey("DrivingLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoeretoejsManager.Api.Models.User", "User")
                        .WithMany("UserDrivingLicense")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrivingLicense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KoeretoejsManager.Api.Models.DrivingLicense", b =>
                {
                    b.Navigation("UserDrivingLicense");
                });

            modelBuilder.Entity("KoeretoejsManager.Api.Models.User", b =>
                {
                    b.Navigation("UserDrivingLicense");
                });
#pragma warning restore 612, 618
        }
    }
}
