@KoeretoejsManager.Api_HostAddress = https://localhost:7191

POST {{KoeretoejsManager.Api_HostAddress}}/api/auth/login
Content-Type: application/json
X-Api-Key: IMIDLERTIDIG-API-KEY-1337
{
  "username": "admin",
  "password": "ABBA1234"
}

###


POST {{KoeretoejsManager.Api_HostAddress}}/api/vehicle/search-by-drivers-license
Content-Type: application/json
X-Api-Key: IMIDLERTIDIG-API-KEY-1337

{
  "licenseTypes": ["B"]
}

###


GET {{KoeretoejsManager.Api_HostAddress}}/api/vehicle/all-vehicles
X-Api-Key: IMIDLERTIDIG-API-KEY-1337

###
